default: &default
  adapter: mysql2
  encoding: utf8
  pool: 16
  username: root
  password: rails

development:
  <<: *default
  database: hrm_dev
  # database: user_avatar_test
test:
  <<: *default
  database: hrm_test

production:
  <<: *default
  database: hrm_prod
